apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: telegraf
    app.kubernetes.io/instance: telegraf
  name: telegraf
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
      annotations:
        diun.enable: "true"
    spec:
      nodeSelector:
        agent: "true"
      containers:
      - image: telegraf:1.10.0
        imagePullPolicy: Always
        name: telegraf
        envFrom:
          - secretRef:
              name: telegraf-secrets
        ports:
        - containerPort: 8125
          name: maintain-http
          protocol: TCP
        volumeMounts:
          - name: telegraf-config-volume
            mountPath: /etc/telegraf/telegraf.conf
            subPath: telegraf.conf
            readOnly: true
      restartPolicy: Always
      volumes:
        - name: telegraf-config-volume
          configMap:
            name: telegraf-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: telegraf
  name: telegraf-web
  namespace: monitoring
spec:
  ports:
  - name: telegraf-web
    port: 8125
    protocol: TCP
    targetPort: 8125
  selector:
    app: telegraf
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: URL
