apiVersion: v1
kind: Secret
metadata:
  name: telegraf-secrets
  namespace: monitoring
type: Opaque
stringData:
  INFLUXDB_DB: DB
  INFLUXDB_URL: URL
  INFLUXDB_USER: USERNAME
  INFLUXDB_USER_PASSWORD: PASSWORD