apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Media:
        - Prowlarr:
            icon: prowlarr.png
            href: URL
            description: Index Management
            widget:
              type: prowlarr
              url: URL
              key: KEY

        - Maintainerr:
            icon: plex-alt.png
            href: URL
            description: Clean Up

        - Calendar:
            widget:
              type: calendar
              firstDayInWeek: sunday # optional - defaults to monday
              view: agenda # optional - possible values monthly, agenda
              maxEvents: 10 # optional - defaults to 10
              showTime: true # optional - show time for event happening today - defaults to false
              timezone: America/Chicago # optional and only when timezone is not detected properly (slightly slower performance) - force timezone for ical events (if i>
              integrations: # optional
                - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr, ical
                  service_group: Media # group name where widget exists
                  service_name: Sonarr # service name for that widget
                  color: teal # optional - defaults to pre-defined color for the service (teal for sonarr)
                  params: # optional - additional params for the service
                  unmonitored: true # optional - defaults to false, used with *arr stack

        - Immich:
            icon: immich.png
            href: URL
            description: Photo Manager
            widget:
              type: immich
              url: URL
              key: KEY
              version: 2

    - Servers:
        - Plex:
            icon: plex.png
            href: URL
            description: Watch movies and TV shows.
            server: URL
            widget:
              type: plex
              url: URL
              key: KEY

        - Tautulli:
            icon: tautulli.png
            href: URL
            description: Plex Statistics.
            widget:
              type: tautulli
              url: URL
              key: KEY

        - TrueNas:
            icon: truenas.png
            href: URL
            description: NAS Sever
            widget:
              type: truenas
              url: URL
              key: KEY

        - Guardian:
            icon: plex.png
            href: URL
            description: Plex User Management

        - Proxmox:
            icon: proxmox.png
            href: URL
            description: Virtualization

        - Proxmox Backkup:
            icon: proxmox.png
            href: URL
            description: Backups

        - Pangolin:
            icon: pangolin.png
            href: URL
            description: Reverse Proxy
            widget:
              type: pangolin
              url: URL
              key: KEY
              org: ORG

    - Geek Stuff:
        - Unifi:
            icon: unifi.png
            href: URL
            description: Unifi Network
            widget:
              type: unifi
              url: URL
              username: USERNAME
              password: PASSWORD

        - Homebridge:
            icon: homebridge.png
            href: URL
            description: Homekit
            widget:
              type: homebridge
              url: URL
              username: USERNAME
              password: PASSWORD

        - NextDNS:
            icon: nextdns.png
            href: https://my.nextdns.io/
            description: DNS
            widget:
              type: nextdns
              profile: PROFILE
              key: KEY

        - Grafana:
            icon: grafana.png
            href: URL
            description: Monitoring
            widget:
              type: grafana
              version: 2 # optional, default is 1
              alerts: grafana # optional, default is grafana
              url: URL
              username: ADMIN
              password: PASSWORD

        - Velld:
            icon: postgres.png
            href: URL
            description: Database Backups

        - Files:
            icon: palmr.png
            href: URL
            description: File Sharing

        - Home Assistant:
            icon: home-assistant.png
            href: URL
            description: Home Automation

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "Cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: custom
        url: URL
        target: _blank
    - unifi_console:
        url: URL
        username: USERNAME
        password: PASSWORD
  docker.yaml: ""