apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: backup
  namespace: immich
spec:
  cluster:
    name: immich-db
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io