apiVersion: v1
kind: Namespace
metadata:
  name: immich
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: immich
    app.kubernetes.io/instance: immich
  name: immich
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich
  template:
    metadata:
      labels:
        app: immich
      annotations:
        diun.enable: "true"
        backup.velero.io/backup-volumes-excludes: "immich-nfs-share"
        backup.velero.io/backup-volumes-excludes: "external-nfs-share"
    spec:
      nodeSelector:
        agent: "true"
      containers:
      - image: ghcr.io/immich-app/immich-server:release
        imagePullPolicy: Always
        name: immich
        env:
          - name: DB_HOSTNAME
            value: ""
          - name: DB_PASSWORD
            value: ""
          - name: DB_USERNAME
            value: ""
          - name: DB_DATABASE_NAME
            value: ""
          - name: TZ
            value: "America/Chicago"
          - name: IMMICH_VERSION
            value: "release"
          - name: REDIS_HOSTNAME
            value: ""
          - name: REDIS_DBINDEX
            value: "1"
        ports:
        - containerPort: 2283
          name: immich-http
          protocol: TCP
        resources:
          limits:
            gpu.intel.com/i915: "1"
            cpu: "2500m"
            memory: "6Gi"
          requests:
            gpu.intel.com/i915: "1"
            cpu: "500m"
            memory: "1Gi"
        volumeMounts:
        - mountPath: /data
          name: immich-nfs-share
        - mountPath: /mnt/external
          name: external-nfs-share
      restartPolicy: Always
      volumes:
      - name: immich-nfs-share
        nfs:
          server: URL
          path: /mnt/default/Immich
      - name: external-nfs-share
        nfs:
          server: URL
          path: /mnt/default/opt/Pictures
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: immich
  name: immich-web
  namespace: immich
spec:
  ports:
  - name: immich-web
    port: 2283
    protocol: TCP
    targetPort: 2283
  selector:
    app: immich
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: IP
