apiVersion: v1
kind: Namespace
metadata:
  name: affine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: affine
    app.kubernetes.io/instance: affine
  name: affine
  namespace: affine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: affine
  template:
    metadata:
      labels:
        app: affine
      annotations:
        diun.enable: "true"
    spec:
      nodeSelector:
        agent: "true"
      containers:
      - image: ghcr.io/toeverything/affine:stable
        imagePullPolicy: Always
        env:
          - name: REDIS_SERVER_HOST
            value: ""
          - name: AFFINE_SERVER_HOST
            value: ""
          - name: DATABASE_URL
            value: ""
          - name: AFFINE_INDEXER_ENABLED
            value: "false"
        name: affine-server
#        command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
        ports:
        - containerPort: 3010
          name: affine-http
          protocol: TCP
        volumeMounts:
        - mountPath: /root/.affine/config
          name: affine
      restartPolicy: Always
      volumes:
      - name: affine
        persistentVolumeClaim:
          claimName: affine
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: affine
  name: affine-web
  namespace: affine
spec:
  ports:
  - name: affine-web
    port: 3010
    protocol: TCP
    targetPort: 3010
  selector:
    app: affine
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: URL
