apiVersion: v1
kind: Namespace
metadata:
  name: searxng
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: searxng
    app.kubernetes.io/instance: searxng
  name: searxng
  namespace: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
      annotations:
        diun.enable: "true"
    spec:
      nodeSelector:
        agent: "true"
      containers:
        - env:
            - name: SEARXNG_UWSGI_WORKERS
              value: "4"
            - name: SEARXNG_UWSGI_THREADS
              value: "4"
          image: docker.io/searxng/searxng:latest
          imagePullPolicy: Always
          name: searxng
          ports:
          - containerPort: 8080
            name: searxng-http
            protocol: TCP
          volumeMounts:
            - mountPath: /etc/searxng
              name: searxng
      restartPolicy: Always
      volumes:
      - name: searxng
        persistentVolumeClaim:
          claimName: searxng
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: searxng
  name: searxng-web
  namespace: searxng
spec:
  ports:
  - name: searxng-web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: searxng
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: IP