apiVersion: v1
kind: Namespace
metadata:
  name: pocketid
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pocketid
    app.kubernetes.io/instance: pocketid
  name: pocketid
  namespace: pocketid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pocketid
  template:
    metadata:
      labels:
        app: pocketid
      annotations:
        diun.enable: "true"
    spec:
      nodeSelector:
        agent: "true"
      containers:
      - image: ghcr.io/pocket-id/pocket-id:v1
        imagePullPolicy: Always
        name: pocketid
        env:
          - name: TRUST_PROXY
            value: "true"
          - name: APP_URL
            value: "URL"
        ports:
        - containerPort: 1411
          name: pocketid-http
          protocol: TCP
        volumeMounts:
        - mountPath: /app/data
          name: pocketid
      restartPolicy: Always
      volumes:
      - name: pocketid
        persistentVolumeClaim:
          claimName: pocketid
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pocketid
  name: pocketid-web
  namespace: pocketid
spec:
  ports:
  - name: pocketid-web
    port: 1411
    protocol: TCP
    targetPort: 1411
  selector:
    app: pocketid
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: URL